(() => {
  const $ = (id) => document.getElementById(id);
  const form = $('iesForm');
  const preview = $('iesPreview');
  const canvas = $('curveCanvas');
  const ctx = canvas.getContext('2d');
  const report = $('report');
  const reportPolar = $('reportPolar');
  const reportCtx = reportPolar.getContext('2d');
  const fields = {
    manufacturer: $('manufacturer'), serial: $('serial'), date: $('date'), ledCount: $('ledCount'),
    singleFlux: $('singleFlux'), beamAngle: $('beamAngle'), efficiency: $('efficiency'), length: $('length'),
    width: $('width'), height: $('height'), power: $('power'), notes: $('notes'), iesType: $('iesType')
  };
  const generatedVertical = Array.from({ length: 37 }, (_, i) => i * 5);
  const generatedHorizontal = [0];
  let current = null;
  let uploaded = null;

  function num(value, fallback) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : fallback;
  }

  function fmt(value, digits = 2) {
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) return '-';
    return String(Number(parsed.toFixed(digits)));
  }

  function esc(value) {
    return String(value ?? '').replace(/[&<>]/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[ch]));
  }

  function safeName(value) {
    return String(value || 'luminaire').replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '') || 'luminaire';
  }

  function wrapNumbers(values, perLine = 10) {
    const lines = [];
    for (let i = 0; i < values.length; i += perLine) lines.push(values.slice(i, i + perLine).join(' '));
    return lines.join('\n');
  }

  function getFormData() {
    return {
      manufacturer: fields.manufacturer.value.trim() || 'CDN',
      serial: fields.serial.value.trim() || 'spot01',
      date: fields.date.value.trim() || new Date().toISOString().slice(0, 10).replaceAll('-', ''),
      ledCount: Math.max(1, Math.round(num(fields.ledCount.value, 1))),
      singleFlux: Math.max(0.01, num(fields.singleFlux.value, 1000)),
      beamAngle: Math.min(120, Math.max(0.01, num(fields.beamAngle.value, 120))),
      efficiency: Math.min(1, Math.max(0.01, num(fields.efficiency.value, 1))),
      length: Math.max(0, num(fields.length.value, 0.1)),
      width: Math.max(0, num(fields.width.value, 0.1)),
      height: Math.max(0, num(fields.height.value, 0.1)),
      power: Math.max(0.01, num(fields.power.value, 10)),
      notes: fields.notes.value.trim()
    };
  }

  function rawIntensity(angle, beamAngle) {
    const halfBeam = Math.max(0.005, beamAngle / 2);
    const gaussian = Math.exp(-Math.LN2 * Math.pow(angle / halfBeam, 2));
    const rearFade = angle > 90 ? Math.max(0, 1 - (angle - 90) / 90) : 1;
    return gaussian * rearFade;
  }

  function buildGeneratedCandela(data) {
    const raw = generatedVertical.map((angle) => rawIntensity(angle, data.beamAngle));
    let integral = 0;
    for (let i = 0; i < generatedVertical.length - 1; i += 1) {
      const a1 = generatedVertical[i] * Math.PI / 180;
      const a2 = generatedVertical[i + 1] * Math.PI / 180;
      integral += ((raw[i] * Math.sin(a1) + raw[i + 1] * Math.sin(a2)) / 2) * (a2 - a1);
    }
    const flux = data.ledCount * data.singleFlux * data.efficiency;
    const scale = flux / Math.max(0.0001, 2 * Math.PI * integral);
    return raw.map((value) => value * scale);
  }

  function buildGeneratedIES(data, candela) {
    const lines = [
      'IESNA:LM-63-2002',
      `[TEST] ${data.serial}`,
      '[TESTLAB] CDN Lighting',
      `[ISSUEDATE] ${data.date}`,
      `[MANUFAC] ${data.manufacturer}`,
      `[LUMCAT] ${data.serial}`,
      `[LUMINAIRE] ${data.serial}`,
      '[LAMPCAT] LED',
      `[LAMP] ${data.ledCount} LED, ${fmt(data.singleFlux, 2)} lm each`,
      `[MORE] ${data.notes || 'Generated by CDN IES Editor.'}`,
      'TILT=NONE',
      [data.ledCount, fmt(data.singleFlux * data.efficiency, 4), 1, generatedVertical.length, generatedHorizontal.length, 1, 2, fmt(data.width, 4), fmt(data.length, 4), fmt(data.height, 4)].join(' '),
      `1 1 ${fmt(data.power, 4)}`,
      wrapNumbers(generatedVertical.map((angle) => fmt(angle, 2))),
      wrapNumbers(generatedHorizontal.map((angle) => fmt(angle, 2))),
      wrapNumbers(candela.map((value) => fmt(value, 4)), 8),
      ''
    ];
    return lines.join('\n');
  }

  function decodeIESBuffer(buffer) {
    const decoders = [
      () => new TextDecoder('utf-8', { fatal: true }).decode(buffer),
      () => new TextDecoder('gb18030').decode(buffer),
      () => new TextDecoder('gbk').decode(buffer),
      () => new TextDecoder('utf-8').decode(buffer)
    ];
    for (const decode of decoders) {
      try {
        const text = decode();
        if ((text.match(/\uFFFD/g) || []).length < 3) return text;
      } catch (error) {}
    }
    return new TextDecoder('utf-8').decode(buffer);
  }

  function parseKeywords(lines) {
    const read = (names) => {
      for (const line of lines) {
        const trimmed = line.trim();
        const upper = trimmed.toUpperCase();
        for (const name of names) {
          const key = `[${name}]`;
          if (upper.startsWith(key)) return trimmed.slice(key.length).trim();
        }
      }
      return '';
    };
    return {
      manufacturer: read(['MANUFAC']),
      serial: read(['LUMINAIRE', 'LUMCAT', 'TEST']),
      date: read(['ISSUEDATE', 'TESTDATE'])
    };
  }

  function tokenizePhotometricBody(text) {
    const lines = text.replace(/\r/g, '').split('\n');
    const tiltIndex = lines.findIndex((line) => /^\s*TILT\s*=/i.test(line));
    if (tiltIndex < 0) throw new Error('TILT line not found.');
    const tiltValue = lines[tiltIndex].split('=').slice(1).join('=').trim().toUpperCase();
    let nums = lines.slice(tiltIndex + 1).join(' ')
      .replace(/\[[^\]]+\][^\r\n]*/g, ' ')
      .replace(/,/g, ' ')
      .split(/\s+/)
      .filter(Boolean)
      .map(Number)
      .filter(Number.isFinite);
    if (tiltValue === 'INCLUDE') {
      const tiltCount = Math.max(0, Math.round(nums[0] || 0));
      nums = nums.slice(1 + tiltCount * 2);
    }
    return nums;
  }

  function parseIES(text, fileName = 'uploaded.ies') {
    const normalized = text.replace(/\r/g, '');
    const lines = normalized.split('\n');
    const nums = tokenizePhotometricBody(normalized);
    if (nums.length < 13) throw new Error('IES photometric data is incomplete.');
    let i = 0;
    const lampCount = nums[i++];
    const lumensPerLamp = nums[i++];
    const multiplier = nums[i++];
    const verticalCount = Math.round(nums[i++]);
    const horizontalCount = Math.round(nums[i++]);
    const photometricType = Math.round(nums[i++]);
    const unitsType = Math.round(nums[i++]);
    const width = nums[i++];
    const length = nums[i++];
    const height = nums[i++];
    i += 2;
    const power = nums[i++];
    const verticalAngles = nums.slice(i, i + verticalCount); i += verticalCount;
    const horizontalAngles = nums.slice(i, i + horizontalCount); i += horizontalCount;
    const expected = verticalCount * horizontalCount;
    if (verticalCount <= 0 || horizontalCount <= 0 || nums.length - i < expected) throw new Error(`IES candela matrix is incomplete. Expected ${expected}, got ${nums.length - i}.`);
    const candela = [];
    for (let h = 0; h < horizontalCount; h += 1) {
      candela.push(nums.slice(i, i + verticalCount).map((value) => value * multiplier));
      i += verticalCount;
    }
    return { text: normalized, fileName, lines, keywords: parseKeywords(lines), lampCount, lumensPerLamp, multiplier, verticalAngles, horizontalAngles, photometricType, unitsType, width, length, height, power, candela };
  }

  function makeGeneratedParsed() {
    const data = getFormData();
    const candela = buildGeneratedCandela(data);
    const text = buildGeneratedIES(data, candela);
    return parseIES(text, `${safeName(data.manufacturer)}-${safeName(data.serial)}.ies`);
  }

  function normalizeDegrees(angle) {
    return ((angle % 360) + 360) % 360;
  }

  function nearlyEqual(a, b, tolerance = 0.001) {
    return Math.abs(a - b) <= tolerance;
  }

  function integrateProfileZone(angles, profile, minAngle = -Infinity, maxAngle = Infinity) {
    const pairs = angles.map((angle, index) => ({ angle, value: Math.max(0, profile[index] || 0) })).sort((a, b) => a.angle - b.angle);
    let integral = 0;
    for (let i = 0; i < pairs.length - 1; i += 1) {
      const from = Math.min(Math.abs(pairs[i].angle), Math.abs(pairs[i + 1].angle));
      const to = Math.max(Math.abs(pairs[i].angle), Math.abs(pairs[i + 1].angle));
      if (to <= minAngle || from >= maxAngle) continue;
      const a1 = Math.abs(pairs[i].angle) * Math.PI / 180;
      const a2 = Math.abs(pairs[i + 1].angle) * Math.PI / 180;
      const y1 = pairs[i].value * Math.sin(a1);
      const y2 = pairs[i + 1].value * Math.sin(a2);
      integral += Math.abs(((y1 + y2) / 2) * (a2 - a1));
    }
    return integral;
  }

  function integrateAngularSeries(pairs, closeCircle = false) {
    if (pairs.length < 2) return 0;
    let integral = 0;
    for (let i = 0; i < pairs.length - 1; i += 1) integral += ((pairs[i].value + pairs[i + 1].value) / 2) * Math.abs(pairs[i + 1].angle - pairs[i].angle) * Math.PI / 180;
    if (closeCircle) integral += ((pairs[pairs.length - 1].value + pairs[0].value) / 2) * Math.abs((pairs[0].angle + 360) - pairs[pairs.length - 1].angle) * Math.PI / 180;
    return integral;
  }

  function integrateHorizontal(data, valuesByPlane) {
    if (data.horizontalAngles.length <= 1) return 2 * Math.PI * (valuesByPlane[0] || 0);
    const pairs = data.horizontalAngles.map((angle, index) => ({ angle: data.photometricType === 1 ? normalizeDegrees(angle) : angle, value: valuesByPlane[index] || 0 }))
      .sort((a, b) => a.angle - b.angle)
      .filter((item, index, array) => index === 0 || !nearlyEqual(item.angle, array[index - 1].angle));
    if (pairs.length <= 1) return 2 * Math.PI * (pairs[0]?.value || 0);
    const first = pairs[0].angle;
    const last = pairs[pairs.length - 1].angle;
    const span = Math.max(0.001, Math.abs(last - first));
    const openIntegral = integrateAngularSeries(pairs, false);
    if (data.photometricType === 1) {
      if (span >= 359.999) return openIntegral;
      if (nearlyEqual(first, 0) && last >= 270) return integrateAngularSeries(pairs, true);
      if (nearlyEqual(first, 0) && nearlyEqual(last, 90)) return openIntegral * 4;
      if (nearlyEqual(first, 0) && nearlyEqual(last, 180)) return openIntegral * 2;
      return openIntegral * (360 / span);
    }
    return openIntegral * (360 / span);
  }

  function fluxOf(data) {
    const verticalIntegrals = data.candela.map((profile) => integrateProfileZone(data.verticalAngles, profile));
    return integrateHorizontal(data, verticalIntegrals);
  }

  function zoneFlux(data, minAngle, maxAngle) {
    const verticalIntegrals = data.candela.map((profile) => integrateProfileZone(data.verticalAngles, profile, minAngle, maxAngle));
    return integrateHorizontal(data, verticalIntegrals);
  }

  function peakOf(data) {
    let peak = { value: -Infinity, hAngle: 0, vAngle: 0 };
    data.candela.forEach((profile, hIndex) => {
      profile.forEach((value, vIndex) => {
        if (value > peak.value) peak = { value, hAngle: data.horizontalAngles[hIndex] || 0, vAngle: data.verticalAngles[vIndex] || 0 };
      });
    });
    return peak;
  }

  function nearestIndex(values, target, cyclic = false) {
    let best = 0;
    let distance = Infinity;
    values.forEach((value, index) => {
      const current = cyclic ? Math.abs((((value - target) % 360) + 540) % 360 - 180) : Math.abs(value - target);
      if (current < distance) { distance = current; best = index; }
    });
    return best;
  }

  function planeIndexTypeC(data, target) {
    const values = data.horizontalAngles;
    const min = Math.min(...values);
    const max = Math.max(...values);
    let mapped = normalizeDegrees(target);
    if (min >= -0.001 && max <= 90.001) {
      mapped %= 180;
      if (mapped > 90) mapped = 180 - mapped;
      return nearestIndex(values, mapped);
    }
    if (min >= -0.001 && max <= 180.001) {
      if (mapped > 180) mapped = 360 - mapped;
      return nearestIndex(values, mapped);
    }
    return nearestIndex(values, mapped, true);
  }

  function nearestPlaneIndex(data, target) {
    return data.photometricType === 1 ? planeIndexTypeC(data, target) : nearestIndex(data.horizontalAngles, target);
  }

  function typeCCurve(data, a, b, label, color) {
    const aIndex = nearestPlaneIndex(data, a);
    const bIndex = nearestPlaneIndex(data, b);
    const aProfile = data.candela[aIndex] || [];
    const bProfile = data.candela[bIndex] || aProfile;
    const forward = data.verticalAngles.map((angle, index) => ({ angle: Math.abs(angle), value: aProfile[index] || 0 }));
    const backward = data.verticalAngles.map((angle, index) => ({ angle: -Math.abs(angle), value: bProfile[index] || 0 })).reverse();
    return { label, color, points: backward.concat(forward) };
  }

  function typeBAngleForDisplay(angle, angles) {
    const min = Math.min(...angles);
    const max = Math.max(...angles);
    return min >= -0.001 && max <= 180.001 && (max - min) > 120 ? angle - 90 : angle;
  }

  function typeBTarget(angles) {
    const min = Math.min(...angles);
    const max = Math.max(...angles);
    return min >= -0.001 && max <= 180.001 && angles.some((angle) => nearlyEqual(angle, 90)) ? 90 : 0;
  }

  function typeBCurveFromPlane(data, target, label, color) {
    const hIndex = nearestPlaneIndex(data, target);
    const profile = data.candela[hIndex] || [];
    return { label: `${label} H${fmt(data.horizontalAngles[hIndex], 1)}`, color, points: data.verticalAngles.map((angle, index) => ({ angle: typeBAngleForDisplay(angle, data.verticalAngles), value: profile[index] || 0 })) };
  }

  function typeBCurveAcrossPlanes(data, target, label, color) {
    const vIndex = nearestIndex(data.verticalAngles, target);
    return { label: `${label} V${fmt(data.verticalAngles[vIndex], 1)}`, color, points: data.horizontalAngles.map((angle, index) => ({ angle: typeBAngleForDisplay(angle, data.horizontalAngles), value: (data.candela[index] || [])[vIndex] || 0 })) };
  }

  function curvesOf(data) {
    if (data.photometricType === 2) return [typeBCurveFromPlane(data, typeBTarget(data.horizontalAngles), 'main vertical', '#ff2b2b'), typeBCurveAcrossPlanes(data, typeBTarget(data.verticalAngles), 'main horizontal', '#58d7ff')];
    return [typeCCurve(data, 0, 180, 'C0/180', '#ff2b2b'), typeCCurve(data, 90, 270, 'C90/270', '#58d7ff')];
  }

  function halfInterpolate(a, b, half) {
    const delta = b.value - a.value;
    if (Math.abs(delta) < 0.000001) return b.angle;
    return a.angle + ((half - a.value) / delta) * (b.angle - a.angle);
  }

  function beamAngleFromPoints(points) {
    const usable = points.filter((point) => Number.isFinite(point.angle) && Number.isFinite(point.value)).sort((a, b) => a.angle - b.angle);
    if (usable.length < 2) return 0;
    const peak = Math.max(...usable.map((point) => point.value), 0);
    if (peak <= 0) return 0;
    const peakIndex = usable.findIndex((point) => point.value === peak);
    const half = peak / 2;
    let left = usable[0].angle;
    let right = usable[usable.length - 1].angle;
    for (let i = peakIndex; i > 0; i -= 1) {
      if (usable[i - 1].value <= half) { left = halfInterpolate(usable[i - 1], usable[i], half); break; }
    }
    for (let i = peakIndex; i < usable.length - 1; i += 1) {
      if (usable[i + 1].value <= half) { right = halfInterpolate(usable[i], usable[i + 1], half); break; }
    }
    return Math.abs(right - left);
  }

  function drawPolar(targetCanvas, targetCtx, data, title, subtitle, footer, showDark = true) {
    const cssSize = Math.max(320, Math.round(targetCanvas.clientWidth || 560));
    const ratio = Math.min(window.devicePixelRatio || 1, 2);
    targetCanvas.width = Math.round(cssSize * ratio);
    targetCanvas.height = Math.round(cssSize * ratio);
    targetCtx.setTransform(ratio, 0, 0, ratio, 0, 0);
    targetCtx.clearRect(0, 0, cssSize, cssSize);
    targetCtx.fillStyle = showDark ? '#0e1216' : '#ffffff';
    targetCtx.fillRect(0, 0, cssSize, cssSize);
    const curves = curvesOf(data);
    const peak = peakOf(data);
    const max = Math.max(peak.value, ...curves.flatMap((curve) => curve.points.map((point) => point.value)), 1);
    const top = 92;
    const bottom = 64;
    const available = cssSize - top - bottom;
    const cx = cssSize / 2;
    const cy = top + available / 2;
    const radius = Math.max(72, Math.min(cssSize * 0.34, available / 2 - 18));
    targetCtx.strokeStyle = showDark ? 'rgba(255,255,255,0.13)' : '#222';
    targetCtx.lineWidth = 1;
    for (let ring = 1; ring <= 4; ring += 1) {
      targetCtx.beginPath();
      targetCtx.arc(cx, cy, radius * ring / 4, 0, Math.PI * 2);
      targetCtx.stroke();
    }
    for (let angle = -180; angle < 180; angle += 15) {
      const rad = angle * Math.PI / 180;
      targetCtx.beginPath();
      targetCtx.moveTo(cx, cy);
      targetCtx.lineTo(cx + Math.sin(rad) * radius, cy + Math.cos(rad) * radius);
      targetCtx.stroke();
    }
    targetCtx.fillStyle = showDark ? '#aeb7c2' : '#111';
    targetCtx.font = '12px Segoe UI, Arial';
    targetCtx.textAlign = 'center';
    targetCtx.textBaseline = 'middle';
    [-150, -120, -90, -60, -30, 0, 30, 60, 90, 120, 150, 180].forEach((angle) => {
      const rad = angle * Math.PI / 180;
      targetCtx.fillText(String(angle), cx + Math.sin(rad) * (radius + 25), cy + Math.cos(rad) * (radius + 25));
    });
    curves.forEach((curve) => {
      targetCtx.strokeStyle = curve.color;
      targetCtx.lineWidth = 2.5;
      targetCtx.beginPath();
      curve.points.forEach((point, index) => {
        const rad = point.angle * Math.PI / 180;
        const r = radius * (point.value / max);
        const x = cx + Math.sin(rad) * r;
        const y = cy + Math.cos(rad) * r;
        if (index === 0) targetCtx.moveTo(x, y); else targetCtx.lineTo(x, y);
      });
      targetCtx.stroke();
    });
    const beam = beamAngleFromPoints(curves[0]?.points || []);
    targetCtx.textAlign = 'left';
    targetCtx.textBaseline = 'alphabetic';
    targetCtx.fillStyle = showDark ? '#dce4eb' : '#111';
    targetCtx.font = '18px Segoe UI, Arial';
    targetCtx.fillText(title, 28, 34);
    targetCtx.fillStyle = showDark ? '#aeb7c2' : '#222';
    targetCtx.font = '13px Segoe UI, Arial';
    targetCtx.fillText(subtitle, 28, 56);
    targetCtx.fillText(`Beam angle: ${fmt(beam, 2)}°`, 28, 76);
    targetCtx.textAlign = 'right';
    targetCtx.fillText(`Scale max ${fmt(max, 1)} cd`, cssSize - 28, 56);
    targetCtx.textAlign = 'left';
    targetCtx.fillText(footer, 28, cssSize - 26);
  }

  function updateStats(data) {
    const flux = fluxOf(data);
    const peak = peakOf(data);
    const beam = beamAngleFromPoints(curvesOf(data)[0]?.points || []);
    $('totalFlux').textContent = `${fmt(flux, 1)} lm`;
    $('maxCd').textContent = `${fmt(peak.value, 1)} cd`;
    $('efficacy').textContent = data.power > 0 ? `${fmt(flux / data.power, 1)} lm/W` : '-';
    $('beamValue').textContent = `${fmt(beam, 2)}°`;
    $('beamLabel').textContent = `${typeName(data.photometricType)} / H ${fmt(data.horizontalAngles[0], 1)} to ${fmt(data.horizontalAngles[data.horizontalAngles.length - 1], 1)} / V ${fmt(data.verticalAngles[0], 1)} to ${fmt(data.verticalAngles[data.verticalAngles.length - 1], 1)} / Beam ${fmt(beam, 2)}°`;
    drawPolar(canvas, ctx, data, data.fileName ? 'Uploaded IES curves' : 'Generated IES curve', `Red: ${curvesOf(data)[0].label} / Blue: ${curvesOf(data)[1]?.label || '-'}`, `Global peak ${fmt(peak.value, 1)} cd @ H${fmt(peak.hAngle, 1)} / V${fmt(peak.vAngle, 1)}`, true);
  }

  function hideReport() {
    report.classList.add('hidden');
  }

  function typeName(type) {
    if (type === 1) return 'Type C';
    if (type === 2) return 'Type B';
    return `Type ${type}`;
  }

  function tableRows(rows) {
    return `<table>${rows.map((row) => `<tr><th>${esc(row[0])}</th><td>${esc(row[1])}</td></tr>`).join('')}</table>`;
  }

  function candelaTable(data) {
    const head = `<tr><th>V / H</th>${data.horizontalAngles.map((angle) => `<th>${fmt(angle, 1)}</th>`).join('')}</tr>`;
    const body = data.verticalAngles.map((angle, vIndex) => `<tr><th>${fmt(angle, 1)}</th>${data.horizontalAngles.map((_, hIndex) => `<td>${fmt((data.candela[hIndex] || [])[vIndex] || 0, 3)}</td>`).join('')}</tr>`).join('');
    return `<table class='wide-table'><thead>${head}</thead><tbody>${body}</tbody></table>`;
  }

  function zonalTable(data) {
    const luminaireLumens = fluxOf(data);
    const lampLumens = data.lampCount * data.lumensPerLamp;
    const zones = [];
    for (let start = 0; start < 180; start += 10) zones.push([`${start}-${start + 10}`, zoneFlux(data, start, start + 10)]);
    const body = zones.map(([zone, lumens]) => `<tr><td>${zone}</td><td>${fmt(lumens, 2)}</td><td>${lampLumens > 0 ? fmt(lumens / lampLumens * 100, 2) : '-'}</td><td>${luminaireLumens > 0 ? fmt(lumens / luminaireLumens * 100, 2) : '-'}</td></tr>`).join('');
    return `<table><thead><tr><th>Zone</th><th>Lumens</th><th>%Lamp</th><th>%Fixt</th></tr></thead><tbody>${body}</tbody></table>`;
  }

  function reportDescription(data) {
    const tiltIndex = data.lines.findIndex((line) => /^\s*TILT\s*=/i.test(line));
    const sourceLines = tiltIndex >= 0 ? data.lines.slice(0, tiltIndex + 1) : data.lines.slice(0, 20);
    return sourceLines.join('\n');
  }

  function buildReport(data) {
    const luminaireLumens = fluxOf(data);
    const lampLumens = data.lampCount * data.lumensPerLamp;
    const peak = peakOf(data);
    const beam = beamAngleFromPoints(curvesOf(data)[0]?.points || []);
    $('reportFileName').textContent = data.fileName || `${safeName(data.keywords.manufacturer || 'CDN')}-${safeName(data.keywords.serial || 'generated')}.ies`;
    $('reportDescription').textContent = reportDescription(data);
    $('reportCharacteristics').innerHTML = tableRows([
      ['Lumens Per Lamp', `${fmt(data.lumensPerLamp, 2)} (${fmt(data.lampCount, 0)} lamp)`],
      ['Total Lamp Lumens', fmt(lampLumens, 2)],
      ['Luminaire Lumens', fmt(luminaireLumens, 2)],
      ['Total Luminaire Efficiency', lampLumens > 0 ? `${fmt(luminaireLumens / lampLumens * 100, 2)} %` : '-'],
      ['Luminaire Efficacy Rating', data.power > 0 ? fmt(luminaireLumens / data.power, 1) : '-'],
      ['Total Luminaire Watts', fmt(data.power, 4)],
      ['Photometric Type', typeName(data.photometricType)],
      ['Beam Angle (FWHM)', `${fmt(beam, 2)}°`],
      ['Maximum Candela', `${fmt(peak.value, 1)} cd @ H${fmt(peak.hAngle, 1)} / V${fmt(peak.vAngle, 1)}`],
      ['Luminous Length', `${fmt(data.length, 4)} m`],
      ['Luminous Width', `${fmt(data.width, 4)} m`],
      ['Luminous Height', `${fmt(data.height, 4)} m`]
    ]);
    $('reportCandela').innerHTML = candelaTable(data);
    $('reportZonal').innerHTML = zonalTable(data);
    $('reportUGR').textContent = peak.value > 0 ? 'UGR table is not calculated in this browser version. Offending-zone validation can be added later.' : 'Unable to calculate UGR - No candela in offending zones';
    drawPolar(reportPolar, reportCtx, data, 'POLAR GRAPH', `#1 ${curvesOf(data)[0].label} / #2 ${curvesOf(data)[1]?.label || '-'}`, `Maximum Candela = ${fmt(peak.value, 1)} Located At Horizontal Angle = ${fmt(peak.hAngle, 1)}, Vertical Angle = ${fmt(peak.vAngle, 1)}`, false);
    report.classList.remove('hidden');
    report.scrollIntoView({ behavior: 'smooth', block: 'start' });
  }

  function setUploadedFields(data) {
    fields.manufacturer.value = data.keywords.manufacturer || 'CDN';
    fields.serial.value = data.keywords.serial || 'uploaded-ies';
    fields.date.value = data.keywords.date || '';
    fields.ledCount.value = String(Math.max(1, Math.round(data.lampCount || 1)));
    fields.singleFlux.value = fmt(data.lumensPerLamp || 0, 3);
    fields.efficiency.value = data.lumensPerLamp > 0 ? fmt(fluxOf(data) / Math.max(0.001, data.lampCount * data.lumensPerLamp), 3) : '1';
    fields.length.value = fmt(data.length || 0, 4);
    fields.width.value = fmt(data.width || 0, 4);
    fields.height.value = fmt(data.height || 0, 4);
    fields.power.value = fmt(data.power || 0, 4);
    fields.beamAngle.value = fmt(beamAngleFromPoints(curvesOf(data)[0]?.points || []), 2);
    fields.iesType.value = `${typeName(data.photometricType)} / parsed / H ${fmt(data.horizontalAngles[0], 1)} to ${fmt(data.horizontalAngles[data.horizontalAngles.length - 1], 1)} / V ${fmt(data.verticalAngles[0], 1)} to ${fmt(data.verticalAngles[data.verticalAngles.length - 1], 1)} / ${data.horizontalAngles.length} x ${data.verticalAngles.length}`;
    fields.notes.value = 'Uploaded IES file. Original photometric data is preserved.';
  }

  function updateGeneratedPreview() {
    current = makeGeneratedParsed();
    current.fileName = `${safeName(fields.manufacturer.value || 'CDN')}-${safeName(fields.serial.value || 'spot01')}.ies`;
    preview.textContent = current.text;
    $('fileName').textContent = current.fileName;
    updateStats(current);
  }

  function downloadCurrentIES() {
    const data = uploaded || current || makeGeneratedParsed();
    const blob = new Blob([data.text], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = data.fileName || `${safeName(fields.manufacturer.value || 'CDN')}-${safeName(fields.serial.value || 'spot01')}.ies`;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(link.href);
  }

  function resetFields() {
    uploaded = null;
    fields.manufacturer.value = 'CDN'; fields.serial.value = 'spot01'; fields.date.value = '20260626'; fields.ledCount.value = '1';
    fields.singleFlux.value = '1000'; fields.beamAngle.value = '120'; fields.efficiency.value = '1'; fields.length.value = '0.1';
    fields.width.value = '0.1'; fields.height.value = '0.1'; fields.power.value = '10'; fields.notes.value = 'Generated by CDN IES Editor.';
    fields.iesType.value = 'Generated Type C / symmetric';
    hideReport();
    updateGeneratedPreview();
  }

  form.addEventListener('input', () => { uploaded = null; hideReport(); updateGeneratedPreview(); });
  $('downloadBtn').addEventListener('click', downloadCurrentIES);
  $('reportBtn').addEventListener('click', () => { if (!uploaded) updateGeneratedPreview(); buildReport(uploaded || current); });
  $('copyBtn').addEventListener('click', () => navigator.clipboard.writeText(preview.textContent));
  $('resetBtn').addEventListener('click', resetFields);
  $('upload').addEventListener('change', (event) => {
    const file = event.target.files && event.target.files[0];
    if (!file) return;
    const reader = new FileReader();
    reader.onload = () => {
      try {
        uploaded = parseIES(decodeIESBuffer(reader.result), file.name);
        current = uploaded;
        setUploadedFields(uploaded);
        preview.textContent = uploaded.text;
        $('fileName').textContent = file.name;
        updateStats(uploaded);
        buildReport(uploaded);
      } catch (error) {
        fields.iesType.value = `Read failed: ${error.message || error}`;
      }
    };
    reader.readAsArrayBuffer(file);
  });
  window.addEventListener('resize', () => { if (current) updateStats(current); if (!report.classList.contains('hidden') && (uploaded || current)) drawPolar(reportPolar, reportCtx, uploaded || current, 'POLAR GRAPH', 'Photometric report graph', 'Resized', false); });
  updateGeneratedPreview();
  hideReport();
})();
