(() => {
  const $ = (id) => document.getElementById(id);
  const verticalAngles = Array.from({ length: 181 }, (_, i) => i);
  const horizontalAngles = [0];

  function num(value, fallback) {
    const parsed = Number(value);
    return Number.isFinite(parsed) ? parsed : fallback;
  }

  function fmt(value, digits = 4) {
    const parsed = Number(value);
    if (!Number.isFinite(parsed)) return '0';
    return String(Number(parsed.toFixed(digits)));
  }

  function safeName(value) {
    return String(value || 'luminaire').replace(/[^a-z0-9_-]+/gi, '-').replace(/^-+|-+$/g, '') || 'luminaire';
  }

  function wrapNumbers(values, perLine = 10) {
    const lines = [];
    for (let i = 0; i < values.length; i += perLine) lines.push(values.slice(i, i + perLine).join(' '));
    return lines.join('\n');
  }

  function formData() {
    return {
      manufacturer: $('manufacturer')?.value.trim() || 'CDN',
      serial: $('serial')?.value.trim() || 'spot01',
      date: $('date')?.value.trim() || new Date().toISOString().slice(0, 10).replaceAll('-', ''),
      ledCount: Math.max(1, Math.round(num($('ledCount')?.value, 1))),
      singleFlux: Math.max(0.01, num($('singleFlux')?.value, 1000)),
      beamAngle: Math.min(120, Math.max(0.01, num($('beamAngle')?.value, 120))),
      efficiency: Math.min(1, Math.max(0.01, num($('efficiency')?.value, 1))),
      length: Math.max(0, num($('length')?.value, 0.1)),
      width: Math.max(0, num($('width')?.value, 0.1)),
      height: Math.max(0, num($('height')?.value, 0.1)),
      power: Math.max(0.01, num($('power')?.value, 10)),
      notes: $('notes')?.value.trim() || ''
    };
  }

  function rawIntensity(angle, beamAngle) {
    const halfBeam = Math.max(0.005, beamAngle / 2);
    const gaussian = Math.exp(-Math.LN2 * Math.pow(angle / halfBeam, 2));
    const rearFade = angle > 90 ? Math.max(0, 1 - (angle - 90) / 90) : 1;
    return gaussian * rearFade;
  }

  function candelaFor(data) {
    const raw = verticalAngles.map((angle) => rawIntensity(angle, data.beamAngle));
    let integral = 0;
    for (let i = 0; i < verticalAngles.length - 1; i += 1) {
      const a1 = verticalAngles[i] * Math.PI / 180;
      const a2 = verticalAngles[i + 1] * Math.PI / 180;
      integral += ((raw[i] * Math.sin(a1) + raw[i + 1] * Math.sin(a2)) / 2) * (a2 - a1);
    }
    const luminaireFlux = data.ledCount * data.singleFlux * data.efficiency;
    const scale = luminaireFlux / Math.max(0.0001, 2 * Math.PI * integral);
    return raw.map((value) => value * scale);
  }

  function buildIES(data, candela) {
    return [
      'IESNA:LM-63-2002',
      `[TEST] ${data.serial}`,
      '[TESTLAB] CDN Lighting',
      `[ISSUEDATE] ${data.date}`,
      `[MANUFAC] ${data.manufacturer}`,
      `[LUMCAT] ${data.serial}`,
      `[LUMINAIRE] ${data.serial}`,
      '[LAMPCAT] LED',
      `[LAMP] ${data.ledCount} LED, ${fmt(data.singleFlux, 2)} lm each`,
      `[MORE] ${data.notes || 'Generated by CDN IES Editor.'}`,
      'TILT=NONE',
      [data.ledCount, fmt(data.singleFlux, 4), 1, verticalAngles.length, horizontalAngles.length, 1, 2, fmt(data.width, 4), fmt(data.length, 4), fmt(data.height, 4)].join(' '),
      `1 1 ${fmt(data.power, 4)}`,
      wrapNumbers(verticalAngles.map((angle) => fmt(angle, 2))),
      wrapNumbers(horizontalAngles.map((angle) => fmt(angle, 2))),
      wrapNumbers(candela.map((value) => fmt(value, 4)), 8),
      ''
    ].join('\n');
  }

  function generatedFileName(data) {
    return `${safeName(data.manufacturer)}-${safeName(data.serial)}.ies`;
  }

  function updateGeneratedIES1Degree() {
    const upload = $('upload');
    if (upload && upload.files && upload.files.length) return;
    const preview = $('iesPreview');
    if (!preview) return;
    const data = formData();
    const candela = candelaFor(data);
    preview.textContent = buildIES(data, candela);
    const fileName = $('fileName');
    if (fileName) fileName.textContent = generatedFileName(data);
  }

  function downloadGeneratedIES(event) {
    const upload = $('upload');
    if (upload && upload.files && upload.files.length) return;
    updateGeneratedIES1Degree();
    const preview = $('iesPreview');
    if (!preview || !preview.textContent.trim()) return;
    event.preventDefault();
    event.stopImmediatePropagation();
    const data = formData();
    const blob = new Blob([preview.textContent], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = generatedFileName(data);
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(link.href);
  }

  window.addEventListener('DOMContentLoaded', () => {
    const form = $('iesForm');
    if (form) form.addEventListener('input', () => setTimeout(updateGeneratedIES1Degree, 0));
    const reportBtn = $('reportBtn');
    if (reportBtn) reportBtn.addEventListener('click', () => setTimeout(updateGeneratedIES1Degree, 0));
    const downloadBtn = $('downloadBtn');
    if (downloadBtn) downloadBtn.addEventListener('click', downloadGeneratedIES, true);
    setTimeout(updateGeneratedIES1Degree, 0);
  });
})();
