'use strict';
const assert = require('node:assert/strict');
const api = require('./build-info.js');
const info = api.getBuildInfo();
assert.equal(info.applicationVersion, '1.0.0');
assert.equal(info.recipeSchemaVersion, 2);
assert.equal(info.dataVersions.alphaOpic, 'CIE S 026:2018 1 nm');
assert.ok(Object.isFrozen(info));
assert.ok(Object.isFrozen(info.dataVersions));
console.log('build info tests passed');
